### ISSUE TITLE
pixivへの投稿

### ISSUE THREAD

**Issue by nnawakearuka** [trysaildaisuki/DigitalTattooTwitterMedia#9]
完全に草案だけどイラストだったらpixivに自動で投稿するとかできないかな

アニメキャラか人か判定するAI
https://aimaker.io/app/image-classification/id/5538
ここでアニメキャラと判断されたらpixivに投稿するとか

pixivpyというライブラリあるけどイラスト投稿機能はないかも

あと規約とか調べた方がいいかもしれない

**Comment by trysaildaisuki** [comment]
え、完全な転載？
す消bやっといてどの口が言うんだって感じだけど、それは流石にヤバくね？
